repos:
- repo: https://github.com/fastai/nbdev
  rev: 2.2.10
  hooks:
  - id: nbdev_clean


- repo: local
  hooks:
    - id: ipynb_to_md
      name: ipynb_to_md
      description: Convert jupyter notebooks to markdown.
      entry: sh scripts/ipynb_to_md.sh
      language: system
